---
- include: merge_vars.yml
  tags:
    - always

- include: install_packages.yml
  tags:
    - packages

- include: start_services.yml
  tags:
    - services

- name: Create a network
  docker_network:
    name: "{{ docker.network_name }}"
    driver: bridge
